version: '3.8'

services:
  flask-app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    container_name: mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
